sudo: false

language: scala

jdk:
    - oraclejdk8

scala:
    - 2.12.3
    - 2.11.11

install:
  - pip install --user codecov

script:
    - sbt ++$TRAVIS_SCALA_VERSION clean coverage test;
    - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && sbt updateImpactSubmit || true'

after_success:
    - codecov
